language: objective-c
osx_image: xcode8.3
cache:
  directories:
    - Carthage
matrix:
  include:
    - env: ACTION=test:osx
      install:
        - gem install xcpretty
        - rake setup PLATFORM=macOS
    - env: ACTION=test:ios
      install:
        - gem install xcpretty
        - rake setup PLATFORM=iOS
    - env: ACTION=test:tvos
      install:
        - gem install xcpretty
        - rake setup PLATFORM=tvOS
    - env: ACTION=build:carthage:ios
    - env: ACTION=build:carthage:macos
    - env: ACTION=build:carthage:tvos
    - env: ACTION=build:carthage:watchos
    - env: ACTION=build:pod
    - env: ACTION=test:package
    - env: ACTION=test:package SWIFT_VERSION=4.0
      osx_image: xcode9
    - env: ACTION=test:package
      os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - eval "$(cat bin/setup-swiftenv.bash)"
        - bin/swiftenv-install
    - env: ACTION=test:package
      os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - eval "$(cat bin/setup-swiftenv.bash)"
        - bin/latest-snapshot '^4.0' >.swift-version
        - bin/swiftenv-install
  fast_finish: true
script: rake "$ACTION"
