disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - force_try
  - function_body_length
  - line_length
  - operator_whitespace
  - type_body_length
  - todo
force_try:
  severity: warning
identifier_name:
  min_length: 2
