# https://github.com/realm/SwiftLint
#
# run on CLI (or as build phase):
#
# swiftlint rules / autocorrect / lint (default)
#
#

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Packages
  - .build

opt_in_rules: # some rules are only opt-in
  - empty_count

disabled_rules: # rule identifiers to exclude from running
- valid_docs   # /// is valid and used by Xcode
- cyclomatic_complexity
- identifier_name
- syntactic_sugar
- type_body_length
- function_body_length
- file_length
- vertical_parameter_alignment
- function_parameter_count
- implicit_getter

line_length: 200

type_name:
  min_length: 2

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
